package.json, packages/docs/.storybook/webpack.config.js, packages/docs/package.json, packages/docs/stories/Tokens/Colors.tsx, packages/styles/package.json, packages/styles/src/tokens.scss, packages/styles/src/tokens.scss.d.ts, yarn.lock
affects: @natds/docs, @natds/styles
=> chore(tokens): creating a demo color tokens page

packages/docs/package.json, packages/docs/src/decorators/jest.tsx, packages/docs/src/mobile/Chip.tsx, packages/docs/src/tokens/Colors.tsx, packages/docs/src/web/Chip.tsx, packages/docs/tslint.json
=> WIP(docs): installing lint on Docs package

packages/web/CONTRIBUTING.md, packages/web/README.md
=> docs(web): updating readme

packages/docs/.storybook/addons.js, packages/docs/.storybook/config.js, packages/docs/package.json, yarn.lock
=> chore(docs): including Viewports addon

packages/web/src/Components/Button.tsx, packages/web/src/__tests__/Button.spec.tsx, packages/web/src/__tests__/__snapshots__/Button.spec.tsx.snap, packages/web/src/index.ts
=> chore(web): creating base Button component

packages/mobile/src/Themes/buildTheme.ts, packages/mobile/src/Themes/index.ts, packages/mobile/src/__tests__/Themes/parsedNaturaLightTheme.json, packages/mobile/src/__tests__/Themes/parsedNaturaLightThemeWithoutValues.json, packages/styles/src/__tests__/themes/natura/parsedNaturaDarkTheme.json, packages/styles/src/__tests__/themes/natura/parsedNaturaLightTheme.json, packages/styles/src/themes/ITheme.ts, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/themes/natura/naturaDarkThemeParsed.json, packages/web/src/__tests__/themes/natura/naturaLightThemeParsed.json
affects: @naturacosmeticos/natds-rn, @naturacosmeticos/natds-styles, @naturacosmeticos/natds-web
=> chore(styles): moving base spacing to Themes

packages/docs/src/mobile/Button/Button.mdx, packages/docs/src/web/Button/Button.mdx
=> chore(docs): removing ZeroHeight info from Button mdx

packages/docs/addons/versions/register.js
=> chore(docs): fixing selected className

packages/docs/addons/versions/styles.css, packages/docs/decorators/container/styles.scss, packages/docs/src/web/Grid/Grid.story.tsx
=> chore(docs): creating grid interactive story

packages/docs/src/tokens/Colors/Colors.story.tsx, packages/docs/src/tokens/Colors/styles.scss, packages/styles/src/__tests__/tokens/colors/natura/parsedNaturaColors.json, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/styles/src/tokens/colors/natura/IColorsNatura.ts, packages/styles/src/tokens/colors/natura/natura.ts
affects: @naturacosmeticos/natds-docs, @naturacosmeticos/natds-styles
=> chore(styles): updating Natura Color tokens

packages/docs/src/web/Button/Button.docs.mdx, packages/docs/src/web/IconButton/IconButton.docs.mdx, packages/docs/src/web/IconButton/IconButton.story.tsx
=> chore(docs): creating IconButton Docs

packages/docs/src/web/ButtonGroup/ButtonGroup.docs.mdx, packages/docs/src/web/ButtonGroup/ButtonGroup.story.tsx
=> chore(docs): creating Docs for ButtonGroup

packages/styles/src/__tests__/tokens/colors/natura/parsedNaturaColors.json, packages/styles/src/tokens/colors/natura/IColorsNatura.ts, packages/styles/src/tokens/colors/natura/natura.ts
affects: @naturacosmeticos/natds-styles
=> chore(styles): updating color tokens to restore gradients

packages/docs/src/tokens/Themes/Natura.tsx, packages/mobile/src/Provider/IThemeShape.ts, packages/mobile/src/Themes/index.ts, packages/mobile/src/__tests__/Themes/buildTheme.spec.ts, packages/mobile/src/__tests__/Themes/index.spec.ts, packages/styles/src/__tests__/themes/natura/natura.spec.ts, packages/styles/src/__tests__/themes/natura/parsedNaturaDarkTheme.json, packages/styles/src/__tests__/themes/natura/parsedNaturaLightTheme.json, packages/styles/src/themes/ITheme.ts, packages/styles/src/themes/natura/typography.ts, packages/web/src/Themes/index.ts, packages/web/src/__tests__/__snapshots__/Button.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/ButtonGroup.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Chip.spec.tsx.snap, packages/web/src/__tests__/themes/natura/natura.spec.tsx, packages/web/src/__tests__/themes/natura/naturaDarkThemeParsed.json, packages/web/src/__tests__/themes/natura/naturaLightThemeParsed.json
affects: @naturacosmeticos/natds-docs, @naturacosmeticos/natds-rn, @naturacosmeticos/natds-styles, @naturacosmeticos/natds-web
=> Feature/Typography Font Branding

packages/docs/src/web/Avatar/Avatar.docs.mdx, packages/docs/src/web/Avatar/Avatar.story.tsx, packages/docs/src/web/Button/Button.docs.mdx, packages/docs/src/web/ButtonGroup/ButtonGroup.docs.mdx, packages/docs/src/web/Grid/Grid.docs.mdx, packages/docs/src/web/IconButton/IconButton.docs.mdx, packages/docs/src/web/Typography/Typography.mdx, packages/web/src/Components/Avatar.tsx, packages/web/src/__tests__/Avatar.spec.tsx, packages/web/src/__tests__/Button.spec.tsx, packages/web/src/__tests__/ButtonGroup.spec.tsx, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Button.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/ButtonGroup.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Chip.spec.tsx.snap, packages/web/src/index.ts
=> chore(web): creating web Avatar

scripts/bump-production-version.sh
This PR fixes the production ci injecting the npm auth token in all of the packages that are published to npm.
- This was not tested, since it is CI only.
=> chore(ci): added npm authentication to the production ci

packages/docs/src/web/Avatar/Avatar.docs.mdx, packages/docs/src/web/Avatar/Avatar.story.tsx, packages/web/src/Components/Avatar.tsx, packages/web/src/__tests__/Avatar.spec.tsx, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap
[Component | Avatar Colors [Web]](https://natura.atlassian.net/secure/RapidBoard.jspa?rapidView=1118&modal=detail&selectedIssue=DSY-285)
Making Avatar receive a `color` property to use in its background color, and making it` primary` color as the default.
=> feat(web): extending Avatar behavior to include theme based Colors

packages/docs/.storybook/manager-head.html, packages/docs/.storybook/theme.js
- [ X] I have performed a self-review of my own code
=> fix(docs): updating storybook theme

.gitignore, packages/docs/src/mobile/TextField/TextField.mdx, packages/docs/src/mobile/TextField/TextField.story.tsx, packages/docs/src/mobile/TextField/sections.tsx, packages/docs/src/mobile/TextField/style.scss, packages/docs/src/web/TextField/sections.tsx, packages/mobile/src/Components/TextField.tsx, packages/mobile/src/__tests__/Componentes/TextField.spec.tsx, packages/mobile/src/__tests__/Componentes/__snapshots__/TextField.spec.tsx.snap, packages/mobile/src/functions.ts
affects: @naturacosmeticos/natds-rn
TextField fixes to comply with the design
=> Fix/Text Field Mobile

packages/web/src/Components/TextField/CustomIcon.tsx, packages/web/src/Components/TextField/Field.tsx, packages/web/src/Components/TextField/PasswordReveal.tsx, packages/web/src/Components/TextField/SearchClear.tsx, packages/web/src/Components/TextField/index.tsx, packages/web/src/Components/TextField/shared.ts, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap
=> fix(web): visual review of TextField web

packages/docs/src/mobile/TextField/TextField.mdx, packages/docs/src/mobile/TextField/TextField.story.tsx, packages/docs/src/mobile/TextField/sections.tsx, packages/mobile/src/Components/TextField.tsx, packages/mobile/src/__tests__/Componentes/__snapshots__/TextField.spec.tsx.snap
affects: @naturacosmeticos/natds-docs, @naturacosmeticos/natds-rn
Fixes color scheme, icon positioning and knobs
=> chore(text-field): fixed mobile TextField color scheme, icon positioning and knobs

packages/web/src/Components/TextField/Field.tsx, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap
Fixing textarea font-family for TextField
=> fix(web): setting font-family for textarea

scripts/bump-production-version.sh
=> chore(ci): fixes ci script for production

packages/web/package.json, scripts/build-release.sh, yarn.lock
Fixes icons import for @material-ui/icons and CI pipeline for storybook production building
- Not tested
=> fix(icons): fixes icons import for material ui and ci pipeline

packages/web/src/Components/TextField/index.tsx, packages/web/src/__tests__/TextField.spec.tsx, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, scripts/bump-production-version.sh
ISSUES CLOSED: #172
When TextField has no label defined and is required, we shouldn't show the label and asterisk.
=> fix(web): fixing TextField label for when is empty and with required

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature_request.md, packages/docs/CHANGELOG.md, packages/docs/package.json, packages/mobile/CHANGELOG.md, packages/mobile/package.json, packages/styles/CHANGELOG.md, packages/styles/package.json, packages/web/CHANGELOG.md, packages/web/package.json, packages/web/src/Components/TextField/index.tsx, packages/web/src/__tests__/TextField.spec.tsx, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, scripts/bump-production-version.sh
=> V0.1.3 v0.2.0

packages/docs/src/web/Fab/Fab.docs.mdx, packages/docs/src/web/Fab/Fab.story.tsx, packages/docs/src/web/Fab/sections.tsx
Changes knobs to comply with the UX perspective
=> docs(docs): changed fabs knobs to comply with UX

.gitattributes, packages/docs/package.json, packages/docs/tsconfig.json, packages/icons/tsconfig.json, packages/mobile/src/__tests__/Componentes/__snapshots__/TextField.spec.tsx.snap, packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/ITheme.ts, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/styles/tsconfig.json, packages/web/src/Components/ContextualBadge.tsx, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/ContextualBadge.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap, packages/web/tsconfig.json
Fixes badge styling for dark mode and naming for theme property
=> fix(badge): fixed badge styling and style property naming

packages/web/src/Components/Typography.tsx
Refactor of the typography component
- No tests were needed
=> refactor(typography): refactored typography component for better usage of the original interface

packages/docs/.storybook/config.js, packages/docs/src/documentation/README.docs.mdx, packages/docs/src/documentation/README.story.tsx, packages/docs/src/icons/Icons.story.tsx
Added documentation section for storybook and simple readme for library usage
=> docs(docs): added a simple readme documentation for the library

packages/docs/addons/theme/provider.js, packages/docs/src/web/Button/Button.story.tsx, packages/docs/src/web/ButtonGroup/ButtonGroup.story.tsx, packages/docs/src/web/Card/Card.story.tsx, packages/docs/src/web/Fab/Fab.story.tsx, packages/docs/src/web/IconButton/IconButton.story.tsx, packages/mobile/src/__tests__/Componentes/__snapshots__/TextField.spec.tsx.snap, packages/mobile/src/__tests__/Themes/__snapshots__/buildTheme.spec.ts.snap, packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/ContextualBadge.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
affects: @naturacosmeticos/natds-docs, @naturacosmeticos/natds-rn, @naturacosmeticos/natds-styles,
@naturacosmeticos/natds-web
Grouping Buttons and updating theme
=> fix(docs): updating Docs and some theme colors

packages/web/src/Components/ContextualBadge.tsx, packages/web/src/Components/Typography.tsx, packages/web/src/Themes/index.ts
Refactor imports for material-ui library
=> refactor(imports): optimized imports for material-ui core

packages/docs/src/web/IconButton/sections.tsx, packages/docs/src/web/ToggleButton/ToggleButton.docs.mdx, packages/docs/src/web/ToggleButton/ToggleButton.story.tsx, packages/docs/src/web/ToggleButton/sections.tsx, packages/web/src/Components/ToggleButton.tsx, packages/web/src/__tests__/IconButton.spec.tsx, packages/web/src/__tests__/ToggleButton.spec.tsx, packages/web/src/__tests__/__snapshots__/ToggleButton.spec.tsx.snap, packages/web/src/index.ts
Creating ToggleButton component
=> feat(web): creating ToggleButton component

packages/docs/src/web/Snackbar/Interactive.tsx, packages/docs/src/web/Snackbar/Snackbar.docs.mdx, packages/docs/src/web/Snackbar/Snackbar.story.tsx, packages/docs/src/web/Snackbar/sections.tsx, packages/mobile/src/__tests__/Componentes/__snapshots__/TextField.spec.tsx.snap, packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-light.ts, packages/web/package.json, packages/web/src/Components/ContextualBadge.tsx, packages/web/src/Components/Snackbar.tsx, packages/web/src/Components/SnackbarContent.tsx, packages/web/src/__tests__/Snackbar.spec.tsx, packages/web/src/__tests__/SnackbarContent.spec.tsx, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/ContextualBadge.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Snackbar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/SnackbarContent.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap, packages/web/src/index.ts, yarn.lock
Adds Snackbar and SnackbarContent component, tests and docs
=> feat(snackbar): added Snackbar and SnackbarContent components

packages/mobile/src/__tests__/Componentes/__snapshots__/TextField.spec.tsx.snap, packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/ContextualBadge.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
Updating themes color palette
- [] I have added tests that prove my fix is effective or that my feature works
=> fix(styles): updating Themes color palette

package.json
Adds the `--stream` flag to the verify script
=> chore(pipeline): fixes the verify pipeline script to show the logs

packages/docs/src/components/Snackbar/Interactive.tsx, packages/docs/src/components/Snackbar/Snackbar.docs.mdx, packages/docs/src/components/Snackbar/sections.tsx
Fixes Snackbar docs due to name change on icons
=> fix(Snackbar): fixes snackbar icons on docs

.gitignore, packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/ITheme.ts, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/ContextualBadge.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
Updating theme's color palette
=> fix(styles): updating theme's color palette

packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap
=> fix(styles): updating dark theme

packages/docs/src/components/AppBar/AppBar.docs.mdx, packages/docs/src/components/AppBar/Interactive.tsx, packages/docs/src/components/AppBar/sections.tsx, packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/Components/AppBar.tsx, packages/web/src/__tests__/AppBar.spec.tsx, packages/web/src/__tests__/__snapshots__/AppBar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
Fixes appbar to comply with https://natura.atlassian.net/browse/DSY-350
=> fix(AppBar): fixes appbar to comply with UX definitions

packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
=> fix(listItem): fixing opacity to ListItem

packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
=> fix(AppBar): fixes AppBar paddings

packages/docs/src/components/Snackbar/Interactive.tsx, packages/docs/src/components/Snackbar/Snackbar.docs.mdx, packages/docs/src/components/Snackbar/Snackbar.story.tsx, packages/docs/src/components/Snackbar/sections.tsx, packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/Components/SnackbarContent.tsx, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/ContextualBadge.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
fixes the error text color, the default snackbar color and adds examples of usage to the snackbar docs
=> fix(Snackbar): fixes snackbar colors and adds examples of usage

packages/web/src/Components/SnackbarContent.tsx
This rollsback the snackbar color scheme change
=> revert(Snackbar): rollback snackbar color scheme change

packages/docs/.storybook/preview-head.html, packages/docs/src/components/Link/Link.docs.mdx, packages/docs/src/components/Link/Link.story.tsx, packages/docs/src/components/Link/sections.tsx, packages/web/src/Components/Link.tsx, packages/web/src/__tests__/__snapshots__/Link.spec.tsx.snap
Including complementary link color as default of the Link component
=> fix(link): including link complementary color for Link component

packages/docs/src/components/Chip/Chip.story.tsx, packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/DrawerHeader.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
Updating Chip Tokens
**Test Configuration**:
* Node version: X.Y.Z
* Yarn version: X.Y.Z
=> fix(chip): updating Chip tokens

.travis.yml, package.json, packages/docs/package.json, packages/icons/package.json, packages/styles/package.json, packages/web/package.json
Removed snapshot update from travis pipeline
=> chore(ci): removed test snapshot updating from travis pipeline

packages/web/src/Components/MenuList.tsx, packages/web/src/Components/Popover.tsx, packages/web/src/index.ts
Exporting material's Popover and MenuList components
=> feat(menu): exporting material Popover and MenuList components

packages/docs/src/components/ExpansionPanel/ExpansionPanel.docs.mdx, packages/docs/src/components/ExpansionPanel/ExpansionPanel.story.tsx, packages/web/src/Components/ExpansionPanel.tsx, packages/web/src/Components/ExpansionPanelActions.tsx, packages/web/src/Components/ExpansionPanelDetails.tsx, packages/web/src/Components/ExpansionPanelSummary.tsx, packages/web/src/__tests__/ExpansionPanel.spec.tsx, packages/web/src/__tests__/__snapshots__/ExpansionPanel.spec.tsx.snap, packages/web/src/index.ts
ExpansionPanel, ExpansionPanelDetails, ExpansionPanelActions, ExpansionPanelSummary components: https://natura.atlassian.net/browse/DSY-377
=> feat(expansion-panel): creating ExpansionPanel component

packages/docs/src/components/Drawer/Drawer.story.tsx, packages/docs/src/components/Drawer/sections.tsx
=> fix(drawer): fixing knobs and contents of the Drawer Docs

packages/web/src/Components/DrawerFooter.tsx, packages/web/src/Components/DrawerMenu.tsx, packages/web/src/__tests__/__snapshots__/DrawerFooter.spec.tsx.snap
=> fix(drawer): updating drawer margins

packages/docs/src/components/Badge/Badge.story.tsx, packages/docs/src/components/Typography/Typography.mdx, packages/web/src/Components/DrawerFooter.tsx, packages/web/src/__tests__/__snapshots__/DrawerFooter.spec.tsx.snap
Updating footer padding
**Test Configuration**:
* Node version: X.Y.Z
* Yarn version: X.Y.Z
=> fix(drawer): updating drawer footer padding

packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/DrawerHeader.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
affects: @naturacosmeticos/natds-styles
Updating badge paddings
=> fix(badge): updating badge paddings

packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/DrawerHeader.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
Updating chip font-size to 14px
=> fix(chip): updating chip font-size

packages/docs/src/components/Menu/Menu.story.tsx, packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/Components/Button.tsx, packages/web/src/Components/Menu.tsx, packages/web/src/Components/MenuItem.tsx, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Card.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Dialog.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/DrawerHeader.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Menu.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
Updating list hover and selected colors
=> fix(menu): updating menu and list hover color

packages/docs/src/components/ExpansionPanel/ExpansionPanel.story.tsx, packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/Menu.spec.tsx, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/DrawerHeader.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Menu.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
Updating expansion panel styles and Menu test
=> fix(expansion-panel): updating styles of Expansion Panel

packages/docs/package.json, packages/docs/src/components/Intro/Intro.docs.mdx, packages/docs/src/components/Intro/Intro.story.tsx, packages/web/src/Components/Intro.tsx, packages/web/src/Components/Typography.tsx, packages/web/src/__tests__/Intro.spec.tsx, packages/web/src/__tests__/__snapshots__/Intro.spec.tsx.snap, packages/web/src/index.ts
Intro component: https://natura.atlassian.net/browse/DSY-379
=> feat(intro): creating Intro component

packages/docs/src/components/ExpansionPanel/ExpansionPanel.story.tsx, packages/docs/src/components/Menu/Menu.story.tsx, packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/DrawerHeader.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Intro.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
Updating menu and list item hover color
=> fix(menu): fixing list/menu item hover color

packages/docs/src/components/ExpansionPanel/ExpansionPanel.story.tsx, packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/DrawerHeader.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Intro.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
Visual review: Updating Expansion Panel layout
=> fix(expansion-panel): updating Expansion Panel layout

packages/docs/src/components/Intro/Intro.docs.mdx, packages/docs/src/components/Intro/Intro.story.tsx, packages/web/src/Components/Intro.tsx, packages/web/src/Components/Typography.tsx, packages/web/src/__tests__/Intro.spec.tsx, packages/web/src/__tests__/__snapshots__/Intro.spec.tsx.snap
Creating color prop for Intro Typography
=> fix(intro): creating color prop for Intro Typography

LICENSE, README.md, packages/docs/README.md, packages/icons/README.md, packages/styles/README.md, packages/web/README.md
affects: @naturacosmeticos/natds-docs, @naturacosmeticos/natds-icons,
@naturacosmeticos/natds-styles, @naturacosmeticos/natds-web
Improving packages readme files
=> fix(readme): updating Icons readme

scripts/build-release.sh
=> fix(travis): fixes ci storybook build for production environment

scripts/build-release.sh
Fixes path resolving on CI script
=> fix(travis): fixed path resolving on ci build-release.sh script

packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/DrawerHeader.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Intro.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
=> fix(expansion-panel): updating disabled state opacity

scripts/build-pre-release.sh
=> fix(travis): fixes travis ci build for alphas

packages/styles/src/__tests__/themes/natura/__snapshots__/natura.spec.ts.snap, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/DrawerHeader.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Fab.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Intro.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/web/src/__tests__/themes/natura/__snapshots__/natura.spec.tsx.snap
One more opacity change.
**Test Configuration**:
* Node version: X.Y.Z
* Yarn version: X.Y.Z
=> fix(expansion-panel): yet another opacity fix

README.md, packages/docs/src/tokens/Themes/TheBodyShop/TheBodyShop.story.tsx, packages/styles/src/__tests__/themes/bodyShop/__snapshots__/theBodyShop.spec.ts.snap, packages/styles/src/__tests__/themes/bodyShop/theBodyShop.spec.ts, packages/styles/src/themes.ts, packages/styles/src/themes/theBodyShop/the-body-shop-dark.ts, packages/styles/src/themes/theBodyShop/the-body-shop-light.ts, packages/styles/src/themes/theBodyShop/typography.ts
Creating The Body Shop Theme
https://natura.atlassian.net/browse/DSY-440
- [X ] New feature (non-breaking change which adds functionality)
=> feat(Theme): creating The Body Shop Theme

packages/docs/package.json, packages/icons/package.json, packages/styles/package.json, packages/web/package.json, yarn.lock
=> chore(packages): updating yarn to resolve security issue warning

packages/docs/src/tokens/shared.ts, packages/styles/src/__tests__/themes/avon/__snapshots__/avon.spec.ts.snap, packages/styles/src/themes/avon/avon-dark.ts, packages/styles/src/themes/avon/avon-light.ts, packages/styles/src/themes/natura/natura-light.ts
affects: @naturacosmeticos/natds-docs, @naturacosmeticos/natds-styles
Updating Avon theme's colors
=> fix(theme): updating Avon theme colors

package.json, packages/docs/package.json, packages/docs/src/components/AppBar/AppBar.docs.mdx, packages/docs/src/components/Breadcrumbs/Breadcrumbs.docs.mdx, packages/docs/src/components/Breadcrumbs/Breadcrumbs.story.tsx, packages/docs/src/components/Breadcrumbs/sections.tsx, packages/docs/src/components/Link/Link.docs.mdx, packages/icons/package.json, packages/styles/package.json, packages/web/package.json, packages/web/src/Components/Breadcrumbs.tsx, packages/web/src/__tests__/Breadcrumbs.spec.tsx, packages/web/src/__tests__/__snapshots__/Breadcrumbs.spec.tsx.snap, packages/web/src/index.ts
Creating Component Breadcrumbs
https://natura.atlassian.net/browse/DSY-442
=> feat(Component Breadcrumbs): creating new component Breadcrombs

CONTRIBUTING.md, packages/docs/src/components/AppBar/AppBar.docs.mdx
=> docs(contributing): added new milestone tutorial

packages/docs/.storybook/config.js, packages/docs/src/all/All.story.tsx
Adding sample page on storybook displaying multiple components to show how themes change the behaviour of components
=> feat(sample): added sample page with multiple components to display theme change

packages/web/src/Components/Avatar.tsx, packages/web/src/__tests__/__snapshots__/Avatar.spec.tsx.snap
=> fix(avatar): fixed contrast text on primary and secondary colors

packages/docs/src/components/Alert/Alert.docs.mdx, packages/docs/src/components/Alert/Alert.story.tsx, packages/docs/src/components/Alert/sections.tsx, packages/web/package.json, packages/web/src/Components/Alert.tsx, packages/web/src/Components/AlertTitle.tsx, packages/web/src/__tests__/Alert.spec.tsx, packages/web/src/__tests__/__snapshots__/Alert.spec.tsx.snap, packages/web/src/index.ts, yarn.lock
added Alert and AlertTitle components
=> feat(alert): added Alert and AlertTitle components

packages/web/src/__tests__/__snapshots__/Card.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/DatePicker.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Dialog.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Drawer.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/List.spec.tsx.snap, packages/web/src/__tests__/__snapshots__/Tab.spec.tsx.snap
=> fix(snapshot): updated component snapshots

packages/docs/src/all/All.story.tsx, packages/docs/src/all/AppBars.tsx, packages/docs/src/all/Avatar.tsx, packages/docs/src/all/Buttons.tsx, packages/docs/src/all/Card.tsx, packages/docs/src/all/Chips.tsx, packages/docs/src/all/IconButtons.tsx, packages/docs/src/all/Tabs.tsx, packages/docs/src/all/TextField.tsx, packages/docs/src/all/styles.ts, yarn.lock
Updated samples page adding more components
=> feat: updated samples page with more components

CONTRIBUTING.md, README.md, yarn.lock
Updated readme and contributing
=> docs: updated contributing and readme

packages/docs/src/components/ButtonGroup/ButtonGroup.docs.mdx, packages/docs/src/components/ButtonGroup/sections.tsx
This changes update de ButtonGroup documentation to show disabled and usages. https://natura.atlassian.net/browse/DSY-516
Check the preview released by CI
=> docs(ButtonGroup): docs refactored to include some variants and usage

packages/docs/src/components/DatePicker/DatePicker.story.tsx, packages/docs/src/components/DatePicker/sections.tsx, packages/docs/src/components/KeyboardDatePicker/KeyboardDatePicker.story.tsx, packages/docs/src/components/KeyboardDatePicker/sections.tsx, packages/web/src/Components/InputStateHelpTextProvider.tsx, packages/web/src/__tests__/KeyboardDatePicker.spec.tsx, packages/web/src/__tests__/__snapshots__/KeyboardDatePicker.spec.tsx.snap
Documented the mobile and desktop Pickers variations. This helps to follow the material guidelines for Mobile https://material.io/components/pickers#mobile-pickers and Desktop https://material.io/components/pickers#desktop-pickers
=> docs(Pickers): documented the desktop and mobile variations for pickers

packages/styles/src/index.ts, packages/styles/src/themes/ITheme.ts, packages/web/src/Components/InputStateHelpTextProvider.tsx, packages/web/src/Themes/index.ts
Reverts natura-cosmeticos/natds-js#325
Travis build failed to deliver new versions of libs in npm
=> Revert "fix(styles): fix interface import path"

.travis.yml
This change remove the env info from travis.yml
=> chore(travis.yml): removed env info

packages/web/package.json
This PR adds `^` to peer dependencies and sort NPM scripts
**Test Configuration**:
* Node version: X.Y.Z
* Yarn version: X.Y.Z
=> [DSY-1093] chore(deps): make peer dependencies more flexible

.gitignore, package.json, stryker.conf.js, yarn.lock
This PR includes support to mutation tests on root package.
* Node version: `12.17.0`
* Yarn version: `1.22.4
=> [DSY-795] Add support to Stryker for mutation tests on root package

.cicd/Jenkinsfile, .cicd/build.sh, .gitignore, package.json
This PR brings the following changes:
- Add...;
- Change 2;
- Change 3.
(Please add a link or reference to a related GitHub/Jira issue)
- Add: `dependency1`;
- Update: `dependency2`;
- Remove: `dependency3`;
---
Describe the tests that you ran to verify your changes:
1. Run...
2. Open...
3. Check if...
- Node.js version (if applicable):
- NPM version (if applicable):
- Yarn version (if applicable):
---
=> chore(pipe) adds build command

.cicd/build.sh
This PR brings the following changes:
- Add...;
- Change 2;
- Change 3.
(Please add a link or reference to a related GitHub/Jira issue)
- Add: `dependency1`;
- Update: `dependency2`;
- Remove: `dependency3`;
---
Describe the tests that you ran to verify your changes:
1. Run...
2. Open...
3. Check if...
- Node.js version (if applicable):
- NPM version (if applicable):
- Yarn version (if applicable):
---
=> chore(pipe): adds some echos to track what is happen

packages/web/docs/icons.md
DSY-1667
This PR brings the following changes:
- Doc file about how to use icons
[DSY-1667 - Criar Documentacão sobre utilização Ícones no ZH](https://natura.atlassian.net/browse/DSY-1667)
No dependencies were added or removed for this change.
---
N/A
N/A
N/A
---
=> DSY-1667 docs: create icons doc

.cicd/build-storybook.sh, .gitignore, CONTRIBUTING.md, package.json, styleguide.config.js, yarn.lock
This PR adds stileguidist to extract the docs while we are unable to do so with storybook.
=> Docs add styleguidist

packages/web/src/Components/Tag/Tag.tsx
Because of the way we created a displayName to Tag (ContextualBadge), the storybook cannot publish a new version of it documentation.
N/A
=> Solving issues to publish storybook

.travis.yml, scripts/build-storybook.sh, scripts/helpers/addVersionOnConfig.js, scripts/helpers/prependVersionToArray.js, scripts/helpers/prependVersionToArray.test.js, scripts/helpers/uniqueArray.js, scripts/helpers/uniqueArray.test.js
Reverts natura-cosmeticos/natds-js#1253
=> Revert "chore: removes older scripts"

lerna.json, packages/web/package.json, packages/web/src/Components/Rating/Rating.argTypes.ts, packages/web/src/Components/Rating/Rating.props.ts, packages/web/src/Components/Rating/Rating.stories.tsx, packages/web/src/Components/Rating/Rating.styles.test.tsx, packages/web/src/Components/Rating/Rating.styles.ts, packages/web/src/Components/Rating/Rating.test.tsx, packages/web/src/Components/Rating/Rating.tsx, packages/web/src/Components/Rating/__fixtures__/sizes.ts, packages/web/src/Components/Rating/__snapshots__/Rating.test.tsx.snap, packages/web/src/Components/Rating/index.ts, packages/web/src/index.ts
https://natura.atlassian.net/browse/DSY-1702
https://natura.atlassian.net/browse/JCF3-843
---
1. Run unit tests.
2. Use storybook in playground tab to validate the component behaviour.
=> feat(rating): add new component

lerna.json
=> chore(pipeline): fixes  mensage

lerna.json, packages/styles/package.json, packages/styles/src/__tests__/themes/avon/__snapshots__/avon.test.ts.snap, packages/styles/src/__tests__/themes/bodyShop/__snapshots__/theBodyShop.test.ts.snap, packages/styles/src/__tests__/themes/natura/__snapshots__/natura.test.ts.snap, packages/styles/src/themes/avon/avon-dark.ts, packages/styles/src/themes/avon/avon-light.ts, packages/styles/src/themes/natura/natura-dark.ts, packages/styles/src/themes/natura/natura-light.ts, packages/styles/src/themes/theBodyShop/the-body-shop-dark.ts, packages/styles/src/themes/theBodyShop/the-body-shop-light.ts, packages/web/package.json, packages/web/src/Components/Divider/Divider.props.ts, packages/web/src/Components/Divider/Divider.stories.tsx, packages/web/src/Components/Divider/Divider.tsx, packages/web/src/Components/Divider/__fixtures__/variants.ts, packages/web/src/Themes/__snapshots__/themes.test.tsx.snap
Following our componentization strategy, this PR represents a refactoring of Divider that removes unused properties (e.g. orientation, light) and fixes color token.
N/A
=> DSY-828: update divider component

packages/web/src/Components/Intro/Intro.tsx
=> chore(intro): pass props to styles

lerna.json, packages/react/.storybook/decorators/themeDecorator.js, packages/react/.storybook/globalTypes/index.js, packages/react/package.json, packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/Divider/Divider.props.ts, packages/react/src/components/Divider/Divider.stories.tsx, packages/react/src/components/Divider/Divider.styles.ts, packages/react/src/components/Divider/Divider.test.tsx, packages/react/src/components/Divider/Divider.tsx, packages/react/src/components/Divider/__snapshots__/Divider.test.tsx.snap, packages/react/src/components/Divider/index.ts, packages/react/src/helpers/StoryContainer.tsx, packages/react/src/index.ts
Create the new Divider component.
=> feat(divider): add new component

packages/react/src/components/Button/Button.styles.ts, packages/react/src/components/Button/__snapshots__/Button.test.tsx.snap
=> chore(button): fix shadow of disabled button contained

.typo-ci.yml, lerna.json, packages/react/.storybook/preview-head.html, packages/react/package.json, packages/react/src/components/Icon/Icon.props.ts, packages/react/src/components/Icon/Icon.stories.tsx, packages/react/src/components/Icon/Icon.styles.ts, packages/react/src/components/Icon/Icon.test.tsx, packages/react/src/components/Icon/Icon.tsx, packages/react/src/components/Icon/__snapshots__/Icon.test.tsx.snap, packages/react/src/components/Icon/index.ts, packages/react/src/index.ts, yarn.lock
=> feat(icon): add new component

.gitignore, lerna.json, packages/react/package.json, packages/react/src/components/Button/Button.props.ts, packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/Button/Button.styles.ts, packages/react/src/components/Button/Button.test.tsx, packages/react/src/components/Button/Button.tsx, packages/react/src/components/Button/__snapshots__/Button.test.tsx.snap, packages/react/src/components/Icon/Icon.props.ts, packages/react/src/components/Icon/Icon.test.tsx, packages/react/src/components/Icon/Icon.tsx
=> feature(button): add showIcon attribute

package.json, yarn.lock
=> chore: downgrade ts-loader

lerna.json, packages/web/package.json, packages/web/src/hooks/useDefaultTheme/index.ts, yarn.lock
=> refactor(natds-web): remove lodash dependencie from getDefaultTheme

package.json, packages/react/babel.config.js, yarn.lock
=> feat: create alias to component

package.json, packages/react/babel.config.js, yarn.lock
Reverts natura-cosmeticos/natds-js#1421
=> Revert "feat: create alias to component"

lerna.json, packages/react/package.json, packages/react/src/components/Button/Button.props.ts, packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/Button/Button.styles.ts, packages/react/src/components/Button/Button.test.tsx, packages/react/src/components/Button/Button.tsx, packages/react/src/components/Button/__snapshots__/Button.test.tsx.snap
=> refactor(button): apply conditional props type

lerna.json, packages/web/package.json, packages/web/src/Components/Counter/Counter.tsx, packages/web/src/Components/Counter/InputCounter.tsx, packages/web/src/Components/Counter/__snapshots__/Counter.test.tsx.snap
=> fix(counter): refactor component to remove warnings 

packages/web/docs/icons.md
=> docs(icons): update instructions to use it

packages/web/docs/icons.md
Reverts natura-cosmeticos/natds-js#1431
=> Revert "docs(icons): update instructions to use it"

lerna.json, packages/web/package.json, packages/web/src/Themes/IThemeWeb.ts, packages/web/src/Themes/IThemesWeb.ts, packages/web/src/Themes/parseTheme.ts, packages/web/src/Themes/themes.ts
co-author: @yasminnvaz
This PR adds breakpoints to the theme interface
=> fix(natds-styles): add breakpoints to the theme interface

CHANGELOG.md, lerna.json, packages/web/CHANGELOG.md, packages/web/docs/icons.md, packages/web/package.json, packages/web/src/Provider/Provider.props.ts, packages/web/src/Themes/IThemeWeb.ts, packages/web/src/Themes/IThemesWeb.ts, packages/web/src/Themes/parseTheme.ts, packages/web/src/Themes/themes.ts
Add breakpoints to the theme interface
=> fix(natds-styles): add breakpoints to the theme interface 

packages/styles/package.json, packages/web/package.json, packages/web/src/Components/Select/Select.props.ts, packages/web/src/Components/Select/Select.stories.tsx, packages/web/src/Components/Select/Select.test.tsx, packages/web/src/Components/Select/Select.tsx, yarn.lock
=> fix(select): accept new option type object

lerna.json, packages/web/package.json, packages/web/src/Components/Button/Button.test.tsx, packages/web/src/Components/Chip/Chip.test.tsx, packages/web/src/Components/DrawerHeader/DrawerHeader.test.tsx, packages/web/src/Components/DrawerMenu/DrawerMenu.props.ts, packages/web/src/Components/DrawerMenu/DrawerMenu.test.tsx, packages/web/src/Components/DrawerMenu/DrawerMenuItem/DrawerMenuItem.props.ts, packages/web/src/Components/DrawerMenu/DrawerMenuSection/DrawerMenuSection.props.ts, packages/web/src/Components/Field/Field.test.tsx, packages/web/src/Components/Field/PasswordReveal/PasswordReveal.test.tsx
=> fix(drawer): change the list type

packages/web/package.json, packages/web/src/Components/Avatar/__snapshots__/Avatar.test.tsx.snap, packages/web/src/Components/Fab/__snapshots__/Fab.test.tsx.snap, packages/web/src/Components/Icon/__snapshots__/Icon.test.tsx.snap, packages/web/src/Components/Intro/__snapshots__/Intro.test.tsx.snap, packages/web/src/Components/Rating/__snapshots__/Rating.test.tsx.snap, packages/web/src/Components/Skeleton/__snapshots__/Skeleton.test.tsx.snap, packages/web/src/Components/SnackbarContent/__snapshots__/SnackbarContent.test.tsx.snap, packages/web/src/Components/Spacing/__snapshots__/Spacing.test.tsx.snap, packages/web/src/Components/Tag/__snapshots__/Tag.test.tsx.snap, packages/web/src/Components/Toolbar/__snapshots__/Toolbar.test.tsx.snap, packages/web/src/Provider/Provider.tsx
This PR fix the generateClassName to work in dev environment;
=> fix(natds-web): update generateClassName to work in dev environment

packages/web/package.json, packages/web/src/Components/Avatar/__snapshots__/Avatar.test.tsx.snap, packages/web/src/Components/Counter/Counter.styles.ts, packages/web/src/Components/Fab/__snapshots__/Fab.test.tsx.snap, packages/web/src/Components/Icon/__snapshots__/Icon.test.tsx.snap, packages/web/src/Components/Intro/__snapshots__/Intro.test.tsx.snap, packages/web/src/Components/Rating/__snapshots__/Rating.test.tsx.snap, packages/web/src/Components/Skeleton/__snapshots__/Skeleton.test.tsx.snap, packages/web/src/Components/SnackbarContent/__snapshots__/SnackbarContent.test.tsx.snap, packages/web/src/Components/Spacing/__snapshots__/Spacing.test.tsx.snap, packages/web/src/Components/Tag/__snapshots__/Tag.test.tsx.snap, packages/web/src/Components/Toolbar/__snapshots__/Toolbar.test.tsx.snap, packages/web/src/Provider/Provider.tsx
This PR fix the Counter input height
=> fix(natds-web): fix the Counter input height

.cicd/release-npm.sh, packages/react/package.json, packages/react/src/ThemeProvider/__snapshots__/buildTheme.test.ts.snap, packages/react/src/ThemeProvider/mock-theme.json, packages/react/src/components/Checkbox/Checkbox.styles.ts, packages/react/src/components/Counter/Counter.styles.ts, packages/react/src/components/Dialog/Dialog.styles.ts, packages/react/src/components/IconButton/IconButton.styles.ts, packages/react/src/components/IconButton/__snapshots__/IconButton.test.tsx.snap, packages/react/src/components/Input/Input.styles.ts, packages/react/src/components/Input/InputAction/__snapshots__/InputAction.test.tsx.snap, packages/react/src/components/RadioButton/RadioButton.styles.ts, packages/react/src/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap, packages/react/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/styles/package.json, yarn.lock
Update the following components with border-radius property:
- Checkbox
- Counter
- Dialog
- IconButton
- TextField
- Radio
=> feat(natds-react): update component borderRadius tokens

.cicd/message-teams.sh
=> chore: update release message script

.cicd/message-teams.sh, packages/react/package.json, packages/react/src/ThemeProvider/index.ts, packages/react/src/index.ts
=> fix(natds-react): exports Theme contract and ReactJSS methods

.eslintrc.js, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/release-drafter.yml, .github/workflows/codeql-analysis.yml, packages/react/package.json, packages/react/src/components/Button/Button.tsx, packages/react/src/components/IconButton/IconButton.tsx
This PR provides some improvements such as
- Resolve lint warnings and update eslint config file
- Update Github issues templates (bug and feature)
- Adding 'dependencies' and 'deps' as maintenance label to Release Drafter
- Remove deprecated step into codeql-analysis action
=> chore: repo improvements

.eslintrc.js, package.json, yarn.lock
=> style: updates lint rules

packages/react/package.json, packages/react/src/components/Avatar/Avatar.props.ts, packages/react/src/components/Avatar/Avatar.stories.tsx, packages/react/src/components/Avatar/Avatar.styles.ts, packages/react/src/components/Avatar/Avatar.test.tsx, packages/react/src/components/Avatar/Avatar.tsx, packages/react/src/components/Avatar/AvatarIcon.tsx, packages/react/src/components/Avatar/AvatarImage.tsx, packages/react/src/components/Avatar/AvatarLabel.tsx, packages/react/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap, packages/react/src/components/Avatar/index.ts, packages/react/src/index.ts
Create a new avatar component following the [ UiKit specs.](https://zeroheight.com/28db352be/p/9629dd-avatar/b/320f01)
=> feat(natds-react): adding a new avatar component

packages/react/package.json, packages/web/package.json, yarn.lock
affects: @naturacosmeticos/natds-react, @naturacosmeticos/natds-web
=> fix: update natds-icons

package.json, yarn.lock
=> chore: remove puppeteer

packages/web/package.json, packages/web/src/Components/LinearProgress/Template.tsx, packages/web/src/Components/Popover/Popover.stories.tsx, packages/web/src/Components/Popover/Template.tsx, yarn.lock
=> fix(natds-web): remove Chromatic

packages/react/package.json, packages/react/src/components/Alert/Alert.props.ts, packages/react/src/components/Alert/Alert.stories.tsx, packages/react/src/components/Alert/Alert.styles.ts, packages/react/src/components/Alert/Alert.test.tsx, packages/react/src/components/Alert/Alert.tsx, packages/react/src/components/Alert/__snapshots__/Alert.test.tsx.snap, packages/react/src/components/Alert/index.ts
Create new Alert component. All colors were defined manual.
=> feat(react): Create Alert component

packages/react/package.json, packages/react/src/components/Select/Select.props.ts, packages/react/src/components/Select/Select.stories.tsx, packages/react/src/components/Select/Select.styles.ts, packages/react/src/components/Select/Select.test.tsx, packages/react/src/components/Select/Select.tsx, packages/react/src/components/Select/__snapshots__/Select.test.tsx.snap, packages/react/src/components/Select/index.ts
=> feat(react): Create Select component

packages/react/src/components/Switch/Switch.props.ts, packages/react/src/components/Switch/Switch.stories.tsx, packages/react/src/components/Switch/Switch.styles.ts, packages/react/src/components/Switch/Switch.test.tsx, packages/react/src/components/Switch/Switch.tsx, packages/react/src/components/Switch/__snapshots__/Switch.test.tsx.snap, packages/react/src/components/Switch/index.ts
New Switch component.
https://natura.atlassian.net/browse/JESS-1748?atlOrigin=eyJpIjoiNjQ4MWM1OWMxZTU5NDU0OTgxZjMyZWY5NzIxYmU2YjMiLCJwIjoiaiJ9
=> feat(natds-react): adds new Switch component

packages/react/package.json
=> fix: update version

packages/react/src/components/Switch/Switch.stories.tsx
=> Dsy 999 normalize version

package.json
=> docs: update private true

packages/react/src/components/Switch/Switch.stories.tsx
=> docs: comment for test

packages/react/package.json
=> doc: bump version

packages/react/package.json, packages/react/src/components/Drawer/Drawer.styles.ts, packages/react/src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
- add prop color
Component Drawer received color highEmphasis property
=> fix: component Drawer add color prop

packages/react/package.json, yarn.lock
=> chore:(natds-themes): version 0.43.1 to 0.44.7

packages/react/package.json, packages/react/src/components/Drawer/Drawer.styles.ts
=> fix: cover version

packages/react/package.json, yarn.lock
affects: @naturacosmeticos/natds-themes
DSY-3141
add new logo consultoriaDebeleza
=> chore(natds-themes): 0.44.7 to 0.46.0 add new logo CB

packages/react/package.json, packages/react/src/components/Drawer/Drawer.styles.ts
=> Dsy 3141 ver

packages/react/package.json, yarn.lock
affects: @naturacosmeticos/natds-themes
DSY-3158
update natds-themes
=> fix(natds-react): version themes 0.46.0 to 0.46.2

packages/react/package.json, packages/react/src/components/Drawer/Drawer.styles.ts
=> Dsy 3158 v2

packages/react/package.json
=> fix(natds-react): version 2.41.1

packages/react/.storybook/globalTypes/index.js, packages/react/package.json, yarn.lock
DSY-3151
update theme with Casa & estilo
=> feat(natds-themes): update theme with casaeestilo

packages/react/package.json, packages/react/src/Templates/Checkout/Search/index.tsx, packages/react/src/ThemeProvider/__snapshots__/buildTheme.test.ts.snap, packages/react/src/components/Alert/Alert.styles.ts, packages/react/src/components/Alert/__snapshots__/Alert.test.tsx.snap, packages/react/src/components/Autocomplete/Autocomplete.styles.ts, packages/react/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/react/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap, packages/react/src/components/Counter/__snapshots__/Counter.test.tsx.snap, packages/react/src/components/Label/Label.styles.ts, packages/react/src/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap, packages/react/src/components/Rating/__snapshots__/Rating.test.tsx.snap, packages/react/src/components/Shortcut/__snapshots__/Shortcut.test.tsx.snap, packages/react/src/components/Snackbar/Snackbar.styles.ts, packages/react/src/components/Snackbar/__snapshots__/Snackbar.test.tsx.snap, packages/react/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/react/src/components/Typography/Typography.styles.ts, packages/react/src/components/Typography/Typography.test.tsx, packages/react/src/components/Typography/__snapshots__/Typography.test.tsx.snap, yarn.lock
Components checkout template evolution
=> Dsy 3319 - components checkout templat evolution

packages/react/package.json, packages/react/src/Templates/Home/LogoButton/LogoButton.styles.tsx, yarn.lock
=> feat(natds-react): add new logo Avon-v2

packages/react/package.json, packages/react/src/components/Counter/Counter.props.ts, packages/react/src/components/Counter/Counter.stories.tsx, packages/react/src/components/Counter/Counter.tsx, packages/react/src/components/Counter/__snapshots__/Counter.test.tsx.snap
add prop readyOnly and onChange in Counter Component
=> Dsy 3677 - add prop readyOnly in Counter Component

packages/react/package.json, packages/react/src/components/Input/Input.styles.ts, packages/react/src/components/Input/__snapshots__/Input.test.tsx.snap, packages/react/src/components/TextField/__snapshots__/TextField.test.tsx.snap
rollback border Textfield pattern 1px focus 2px
=> Dsy 3684 - rollback border Textfield pattern 1px focus 2px

packages/react/.storybook/preview-head.html, packages/react/package.json, yarn.lock
DSY-3609
update Lib Icons to 1.15.0
=> feat(natds-react): update Lib Icons to 1.15.0

packages/react/src/components/Icon/Icon.stories.tsx
=> refactor(natds-react): add stories Icons

packages/react/.storybook/preview-head.html, packages/react/CHANGELOG.md, packages/react/package.json, packages/react/src/components/IconButton/IconButton.stories.tsx, yarn.lock
DSY-3710
add stories search IconButton
=> feat(natds-react): add stories search IconButton

packages/react/.storybook/preview-head.html, packages/react/.storybook/preview.js, packages/react/CHANGELOG.md, packages/react/package.json, packages/react/src/Templates/GlobalTypes/index.ts, packages/react/src/Templates/Login/Login.stories.tsx, packages/react/src/Templates/Login/Login.style.ts, packages/react/src/Templates/Login/Login.tsx, packages/react/src/components/Snackbar/Snackbar.styles.ts, packages/react/src/components/Snackbar/__snapshots__/Snackbar.test.tsx.snap, yarn.lock
Add template Login
Add viewport in storybook
Update lib Icons
=> Dsy 3330 - Add template Login

packages/react/CHANGELOG.md, packages/react/package.json, packages/react/src/components/Button/Button.props.ts, packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/Snackbar/Snackbar.stories.tsx
Establish a component technical documentation standard using "Button"
=> Dsy 3753 - Establish a component technical documentation standard using "Button"

packages/react/CHANGELOG.md
DSY-4005
Update changelog - 2.57.0
=> fix(natds-react): update changelog-react-2.57.0

packages/react/.storybook/manager-head.html, packages/react/package.json
DSY-4260
added Analytic in storybook
=> feat(natds-react): added Analytic in storybook

packages/web/.storybook/decorators/ThemeProviderDecorator/index.js, packages/web/.storybook/globalTypes/index.ts, packages/web/package.json, packages/web/src/Components/Button/Button.props.ts, packages/web/src/Components/Button/Button.styles.ts, packages/web/src/Components/Button/Button.tsx, packages/web/src/Components/Button/__snapshots__/Button.test.tsx.snap, packages/web/src/Components/ButtonGroup/__snapshots__/ButtonGroup.test.tsx.snap, packages/web/src/Components/Card/__snapshots__/Card.test.tsx.snap, packages/web/src/Components/Counter/__snapshots__/Counter.test.tsx.snap, packages/web/src/Components/Menu/__snapshots__/Menu.test.tsx.snap, packages/web/src/Components/Popover/__snapshots__/Popover.test.tsx.snap, packages/web/src/Themes/ThemeBrandName.ts
Dsy 4312 
added natura_v3 theme
added buttonBorderRadius
=> Dsy 4312 added natura_v3 theme

packages/react/CHANGELOG.md
=> update changelog react-js

packages/react/.storybook/preview-head.html, packages/react/package.json, packages/react/src/components/Icon/Icon.stories.tsx, yarn.lock
=> Dsy 4627 update lib Icons

packages/react/package.json, packages/react/src/components/Logo/Logo.stories.tsx, yarn.lock
DSY-5073
feat(natds-react):  added logo fuerzadeventas FV - espanha
=> feat(natds-react):  added logo fuerzadeventas FV - espanha

packages/react/.storybook/preview-head.html, packages/react/package.json, packages/react/src/ThemeProvider/__snapshots__/buildTheme.test.ts.snap, packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/Tab/Tab.stories.tsx, yarn.lock
=> feat(natds-react):  update lib Icons and themes

packages/react/.storybook/preview-head.html, packages/react/package.json, packages/react/src/components/Icon/Icon.styles.ts, yarn.lock
DSY-5288
feat(natds-react):  update lib icons
=> feat(natds-react):  update lib icons

packages/react/.storybook/globalTypes/index.js, packages/react/package.json, packages/react/src/ThemeProvider/__snapshots__/buildTheme.test.ts.snap, packages/react/src/components/Input/Input.styles.ts, packages/react/src/components/Input/InputAction/InputAction.styles.ts, packages/react/src/components/Input/InputAction/__snapshots__/InputAction.test.tsx.snap, packages/react/src/components/Input/__snapshots__/Input.test.tsx.snap, packages/react/src/components/Select/Select.styles.ts, packages/react/src/components/TextField/__snapshots__/TextField.test.tsx.snap, yarn.lock
Dsy 5392 added theme ConsultoriaDeBeleza_v2
Tokens of themes and adjusts
=> Dsy 5392 added theme ConsultoriaDeBeleza_v2

packages/react/src/components/GayaButton/GayaButton.stories.tsx, packages/react/src/components/GayaButton/GayaButton.styles.ts, packages/react/src/components/GayaButton/GayaButton.tsx, packages/react/src/components/GayaButton/__snapshots__/GayaButton.test.tsx.snap
DSY-5430
new triguer jenks
fixed texttransform CB2 e FV2 to none update theme
=> fix(natds-react):  fixed texttransform CB2 e FV2 to none update theme

packages/react/.storybook/preview-head.html, packages/react/package.json, packages/react/src/components/Logo/Logo.tsx, yarn.lock
DSY-5461
fix(natds-react):  update theme fixed Logo CB-V2 AB ES PT-BR
=> fix(natds-react):  update theme Logo CB-V2 AB ES PT-BR

packages/react/.storybook/globalTypes/index.js, packages/react/.storybook/preview-head.html, packages/react/package.json, packages/react/src/ThemeProvider/__snapshots__/buildTheme.test.ts.snap, packages/react/src/components/Badge/__snapshots__/Badge.test.tsx.snap, packages/react/src/components/GayaButton/GayaButton.stories.tsx, packages/react/src/components/GayaButton/GayaButton.tsx, packages/react/src/components/Shortcut/__snapshots__/Shortcut.test.tsx.snap, packages/react/src/components/Snackbar/Snackbar.styles.ts, packages/react/src/components/Tag/__snapshots__/Tag.test.tsx.snap, yarn.lock
=> feat(natds-react):  added Avon-V3

packages/styles/src/themes.ts, packages/styles/src/themes/avon_v3/avon_v3-dark.ts, packages/web/src/Themes/ThemeBrandName.ts
=> Dsy 5581v2 Added Avon-V3 fixed imports

packages/react/.storybook/preview-head.html, packages/react/package.json, packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/GayaButton/GayaButton.stories.tsx, packages/react/src/components/GayaButton/GayaButton.styles.ts, packages/react/src/components/GayaButton/GayaButton.tsx, packages/styles/package.json, packages/styles/src/__tests__/tokens/__snapshots__/tokens.test.ts.snap, yarn.lock
DSY-5778
feat(natds-react):  added 6 new icons and update theme
=> feat(natds-react):  added 6 new icons and update theme

packages/react/src/components/Button/Button.tsx, packages/react/src/components/Select/Select.props.ts, packages/react/src/components/Select/Select.tsx, packages/react/src/components/Select/__snapshots__/Select.test.tsx.snap
=> Dsy 5903v2 fixed Aria-label in select

packages/react/jest.config.js, packages/react/package.json, packages/react/src/growthPlanColors/growthPlanColors.json, packages/react/src/growthPlanColors/growthPlanColors.stories.tsx, packages/react/src/growthPlanColors/growthPlanColors.ts, packages/react/src/index.ts
DSY-5972
feat(natds-react):  added Grow Plan Colors
=> feat(natds-react):  added Grow Plan Colors

packages/react/src/growthPlanColors/growthPlanColors.stories.tsx
=> fix(natds-react):  change description Grawth Plan Colors

packages/react/src/components/Button/Button.props.ts, packages/react/src/components/Logo/Logo.styles.ts
affects: @naturacosmeticos/natds-rn
DSY-6007
fix(natds-rn):  fixed logo CB1
=> fix(natds-rn):  fixed logo CB1

packages/react/.storybook/preview-head.html, packages/react/package.json, packages/react/src/components/GayaButton/GayaButton.stories.tsx, yarn.lock
DSY-6235
Update lib de icons
filled-action-delete
filled-alert-cancel
filled-alert-check
filled-alert-info
filled-alert-warning
filled-content-strawberry
filled-product-mirror-woman
filled-product-shoewoman
outlined-action-delete
outlined-alert-cancel
outlined-alert-check
outlined-alert-info
outlined-alert-warning
outlined-content-strawberry
outlined-product-mirror-woman
outlined-product-shoewoman
=> feat(natds-react): added news icons
